export const PACKAGE_STATUS_MAPPING = {
  '-2': { text: '取消中', textColor: '#cccccc' },
  '-1': { text: '已取消', textColor: '#cccccc' },
  '2': { text: '已申请', textColor: '#0DAF52' },
  '3': { text: '已取件', textColor: '#FFB700' },
  '4': { text: '已返仓', textColor: '#FFB700' },
  '5': { text: '已退款', textColor: '#666666' }
};

// 秒杀状态
export const SEC_KILL_STATUS = {
  'NOT_START': 0,	// 未开始
  'HAS_START': 1,	// 已开始
  'FINISH': 2,	// 已结束
  'NONE': -1	// 无状态
};

// 秒杀用户可买状态
export const GOOD_BUY_STATUS = {
  'READY_SALE': 0,   // 准备开售
  'BUY': 1, // 可购买
  'FINISH': 2,   // 已结束
  'SELL_OUT': 3,   // 已售罄
  'ACTIVITY_NO_START': 4,   // 活动未开始
  'ACTIVITY_IS_END': 5,   // 活动已结束
  'OFFLINE': 6,   // 下线
  'ROB_ALL': 7,   // 已抢光
  'PARTICIPATE': 8,   // 已参与
};


// 魔窗SDK  打开动态链接 mlink短链key
export const MLINK_OPEN_URL = {
  'test': 'https://awx6kj.mlinks.cc/Adyj',
  'stage': 'https://awx6kj.mlinks.cc/Adyj',
  'online': 'https://awx6kj.mlinks.cc/Adyk'
}

// 前后端接口检验时的盐值数组
export const saltList = {
    test: [
            "ff3J]K<y;kg<U'",
            "'ZDWR3F6fNY",
            "OBalO_=d<r)w",
            "reI*Xc7m^O",
            "a.>zbB2e62K7O",
            "8?;S4z3|)1Maq5Z",
            "UV<j#U2|,sq",
            "m,3EW4bNpkJ@x",
            "0n*},bp8QAv9G",
            "{W1@(J7Z5#C1Jx6",
            "`h)1=zQ!3B",
            "<8!,8l{]oMLfbw<",
            "T5cjl9-Zn,he),q",
            "6}KBybUyk@A>YX",
            "VS|Y2~w87uh&",
            "-Eiu6,SZT@[",
            "Ys%Ixi8yF`dBN",
            "_hX`_!WtELLI=xk",
            "9_a|lG.D>JO'g",
            "%rdfhaF(@|}AG",
            "d^BJF9>d6?",
            "apN_GR0tO10b*",
            "zdec!W-~f3A|B",
            "nlL)^|r)lR}y%t",
            "6xWbCa+Q*PJ4k",
            ")m=eSo{T,6",
            "Ol}Wb(PT*6iuho",
            "aM(i:nW>@sTMB",
            "e>!PmL}Qaj;?c",
            "V6JwDCD~Fhexf",
            "qvYT%O~{Q,y",
            "N_wUa=Q8f=VG_h",
            "n>f4Y2>0'{kII^7",
            "k|@,>PbV~=C*",
            "^[#~Z;SH=tQ",
            ",c0PzdR#!PvQ=.",
            "Du[ok8Zr>_5",
            "ZY=vE*__dRI",
            "h1#DB^7<(^2*",
            "oYf``|:>Nff%Mc#",
            "w!1=k|uk[ltRcw",
            "G~l}aR}|o%",
            "l-<9%!M40b>Xi",
            "ZZE7hUiEr`v",
            "tfnx;UpU&m+NR",
            "'(FNMAoP9xEQ@:",
            "iw)l&S6{T!",
            "I@m99pv771",
            "ZEyW]2OXmv",
            "b.cFE{5Xw+4EOF",
            "EAua37)(~kmU5",
            "-?Kl4v}~H%A1",
            "_86A3F`0Ah#",
            "?_w.x.zUxD[uL",
            ",)%sMXugNg.e?dC",
            "c;Yv,n%2BB]#*",
            "^R3@(}z#B~T)",
            "(~`FrUYkEUv=e?",
            ":FDdtkkPO*@",
            "5j,qT!P9^h}}@+m",
            "ZtIrlMZL#|7SY{",
            "rfeQ&:`]VmzL.W",
            "`7u%Hg4mX~K",
            "'fLnwn.7y-",
            "CS*T9Yhcc*N1)^Q",
            "WSU)htTODIa_*",
            "(=xR~;,s7[",
            "TU|,Fj9~_sB",
            "5sTy7S7z{Rpg1}",
            "-T<}`H+-,9v_>``",
            "%!abdv3:~.3A}a<",
            "-Y-pGU2Ae[",
            "O:,Ak5RaN,I",
            "Fg|)ivYN.+RYN",
            ";=Qh-wr+kWkz",
            "SleyT+]<M8N[pP",
            "b6F<<Q3h=dmApy)",
            "aXQeAC_CCqX",
            ":V#yl>FuMiUl>a",
            "B!?A9I*[pGn",
            "H1OGo39yD=2+[`h",
            "=H;}uc9[G[YS",
            "<zFW!pSWhCL",
            "k|991ahz*!-XR",
            "|2+Uo=4BrPxZO",
            "<DYra,!g3i",
            "40&vVd5UbEd",
            "a7Jo8j:lMR0Q_g",
            "7e<,X)lEfq",
            "y[ZwGChwEfIdO",
            "_~^tZP]<HQfTm~H",
            "AC`~5d_<E-",
            ",RT'wH;Z6l",
            "i6M,BZ~Z^SL60",
            "g'r|NIum{IV",
            "{S&{1YHX#]5PF",
            "0^#aVH#3_!_[-",
            "VSdkx|lThUp",
            "3CYuF{trceRG>1i",
            "Gl|ft{*#q=n6"
        ],
    online: [
            "E6x(dyRm0Tu,DYj",
            "V7i@JcXHuM9e",
            "A}eSpm#2drq",
            "id}s'YKA#bI9Ws",
            "NjC<duNpXp4zP3",
            "A-D%FmX&a-",
            "cTFi0x|:dIS",
            "CX:(+?;d.R]?r;",
            "tHtT.dFMJc",
            "(0yLsq4`ql",
            "+?i&h<,!k{:q6hH",
            "{~Ng,T#Q!=86Y1",
            "7n2zb.f8e)%0TvF",
            "*('=C.dG~H1jk",
            "kh]Q;3I8),MBvh",
            "?dlEr=I0pF7]MO",
            ">j^V8.5)X7",
            "W88dd8fL!qoDW",
            "Z57#EqHq['3sYJM",
            "'gABfS-+qGrq",
            "SrG=a,t.Y^&'",
            "veR?NoWVFDHV",
            "Svg,]bb60!",
            "*!ix],:WqX",
            "[eX-0zn.:c",
            "!I5L!mUr1<&K",
            "fz<Ij#f.8&",
            "5t9D38f5M:",
            "yKN_#`AzW_A",
            "*Fxf)ae8%D|",
            "+(d>];xsoY07U",
            "lDZ!YAW4Ww#",
            ">)0_TnPtCg",
            "y[ZosvFa|k-Y",
            "3@>wQo]'SSl|r",
            "3P]+-aoQwlT=",
            "i{xfX)s1{q",
            "c{S)9YQN`1kTR",
            "rNhoLqpq?DWm",
            "BqKHjriKPi#7&6l",
            "T&&fv^f0?h7",
            "la)^Ri?n=H?zM0Y",
            "@x~[O9+}4m(8#",
            "`<I2jd+t=fvm;m",
            "lW!w}eMJ&4psSO!",
            "XX@@,r5u#qOTA",
            "el4I0F+Vc9",
            "ED)s{5YB^+r",
            "=yT`'2u%oxq",
            "^I&CRDz`1d~AgpZ",
            "#NF#)|E{S5`D",
            "K{l~8NyC.+.",
            "`lmpMRp-}<",
            "HA8g4S.5,Y+>Vl",
            "Y;VGwBn,DG",
            "lR^>6OWif#4<.",
            "Dr(D^'Cvy4G'",
            "znfmYvAn]B`l",
            "TWnXc!ICESFU",
            "94kfl(CB0sA:Z",
            "iVyUx|t@GCJ>!*=",
            "zFvMMkOsa9li!y",
            ":Nk[vTB@~*Q%Hc=",
            "u-*Zm.AS<{s",
            ">u&]Jhe%`e%f",
            "2kSg#>jpZa<%y'",
            "rD`hWQxgy-VbQ,",
            "J*3hjId@u>Pw[",
            "fa7:4oyWp*rNV",
            "oH#*7@l[uQ5mHD",
            "bZ}XaRHB=n",
            "}}XU7e!@!{8",
            "<fNa90.:@Ye|9[",
            "g7_;-CJik9",
            "uC;M3G_R2{Z}a@",
            "dFq%!96+`12l}il",
            "DjS>dNlW#^6AzF",
            "~I6YNdRo'!e",
            "3PI&W5aJVJs%t7|",
            "EzEh[lrnn'~&",
            "g]jtb|0y^.",
            "us+6aD|MD(LN",
            "fX{'WY*zXM-5P",
            ",m,ab#xc=H",
            "gwI5-'z5tOx",
            "HT+=qkIE!lfBy3",
            "_fgTLSjTKvaKyOh",
            "?Jx!e3]xD}",
            "5Bk`Bd']2evp}Q-",
            "uV1`*TVY[K'",
            "Pb2#4YFzi!s]x",
            "10yh;M)H*I",
            "#tJT64|M;ncn`P",
            "W}7&q=p:LYnX*",
            "sq[N&_p'F%",
            "#n@Rk^,w9E",
            "DoaBZ8TP>p40rY",
            "Q)EDX);UJ',3",
            "uk:{5(Pp.P)EJ",
            "=)~1u[k;Fa."
        ]
}
